### ISSUE TITLE
Does not revalidate on 14.2

### ISSUE THREAD

**Issue by benjick** [alfonsusac/nextjs-better-unstable-cache#9]
Hello!

I'm facing an issue where I can't revalidate cached data when upgrading to 14.2. Works fine on 14.1.0.

I've created a reproduction for the issue here: https://github.com/benjick/unstable-cache-error-reproduction

**Comment by alfonsusac** [comment]
Hi, the repository is private

**Comment by alfonsusac** [comment]
Thanks, will test this out

**Comment by alfonsusac** [comment]
Ive tried the repo and it works well for me?

Screen Recording 2024-05-11 at 11.20.11 AM.mov

**Comment by alfonsusac** [comment]
No i didnt, ok now i can see it. Ill try to see what causes this 🤔

**Comment by alfonsusac** [comment]
I just discovered what causes this. This is because functions that are exported from "use server" will be converted into async functions. This makes the `() => ['test-case-value]` part to become async and will failed to get read by `memoize`.

I just experimented with it now and I completely understand that its not your fault. But do know that "use server" shouldnt be used to place data fetching function as any function that is exported from that file will become an endpoint.

I will put a warning in the function to better communicate with developers on how they should put their memoize functions.

**Comment by ScreamZ** [comment]
I'm not sure to understand why the callback gets converted to async, it's not exported. Can anyone explains me ?

@benjick Not sure to understand your solution, maybe you could give some examples ? 

Thanks

**Comment by ScreamZ** [comment]
> @ScreamZ hey!
> 
> 
> 
> I split "server actions" and "data" into different files. For server actions I put `"use server"` in the file, for data (where I use memoize) I do not.

Okay so we can say that any defined function within the file, even as inline callback is exported as a server action, probably because of hoisting or something like this ?
